---
title: "ha-adaptation"
author: "Viktor Thunell"
date: '2021-03-29'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
plot(x, kap_fun(x, ha=5), yla = "kappa", type="l", ylim= c(0,1), main = "Size-dependent kappa")
lines(x, kap_fun(x, ha=3), yla = "kappa", type="l", ylim= c(0,1), main = "Size-dependent kappa", col="blue")
lines(x, 1-kap_fun(x, ha=5), ylab = "1-kappa", type="l", main = "Size-dependent 1-kappa", col="red")
lines(x, 1-kap_fun(x, ha=3), ylab = "1-kappa", type="l", main = "Size-dependent 1-kappa", col="blue")
#dev.off()
```

```{r}
dwdt <- function(time, m, Pars) { 
  maintenance <- (rho1*(m^rho2)*rM_T_AL2(Pars['T'], m))   # Maintenance rate at time, mass with Pars
  #ifelse(m > 1, 
  intake <- alpha*Pars['Y']*eps1*(m^eps2)*rI_T_GU2(Pars['T'], m)#,
  #    intake <- (alpha*Y2*eps1*(m^eps2)*rI_T_GU2(Pars['T'], m))) # Intake energy rate at time, mass with Pars, NOTE intake rate multiplied with alpha and Y
  mass <- kap_fun(m,Pars["kappa"],Pars["ha"])*intake - maintenance    # Growth rate at time, mass with Pars
  #mass <- Pars['kappa']*intake - maintenance    # Growth rate at time, mass with Pars
  return(list(mass, maintenance, intake)) # return all rates
}

DEBrepfun <- function(m, Pars, e_m = 0.00351388) { # Note that intake refers to net energy available for growth, reproduction and maintenance
  Devm = 374 # *(1 - pars[["kappa"]])
  fecund <- function(m, Pars, e_m) {
    f <- ratefun(m, Pars)
    f <- ifelse(f[,"mass",] < Devm,  0, #is it mature? # see text for the following conditions...
                ifelse(kap_fun(m,Pars["kappa"],Pars["ha"])*f[,"intake",] >= f[,"maintenance",], f[,"intake",]*(1-kap_fun(m,Pars["kappa"],Pars["ha"])), #can available energy from intake cover maintenance, NOTE:intake is already scaled with Y*alpha
                       ifelse(kap_fun(m,Pars["kappa"],Pars["ha"])*f[,"intake",] < f[,"maintenance",] & (f[,"maintenance",] <= f[,"intake",]),
                              (1-kap_fun(m,Pars["kappa"],Pars["ha"]))*f[,"intake",] + kap_fun(m,Pars["kappa"],Pars["ha"])*f[,"intake",] - f[,"maintenance",], 0)))
    sum(f)/e_m * 0.5 #- 10*y^0.6# Summed energy allocated to reproduction reserve in one season diveded by egg weight and 0.5 from sex ratio (half of the eggs are female)
  }
  sapply(m, fecund, Pars, e_m)
}
```

```{r}
Temp = seq(285,289,2)
t <- 18
traj <- NULL
#cM <- 0.00
cId <- 0
#EaI
#cIas <- c(-0.005,0,0.005)
has <- c(3,5,7)
for(o in has){
   ha = o
for(i in Temp){
  trajT <- as.data.frame(cbind(ProjCoh(c(T = i, kappa = 0.81, Y = 1, ha=o),t, I_pop=c(1000000,rep(0,n))),rep(c(0,round(x)),t),i,o))
  colnames(trajT) <- c("abund","t","mass","Temp","cIa")
  trajT <- 
    trajT %>% 
    group_by(t) %>%
     slice(which.max(abund)) 
  traj <- rbind(traj, trajT)
} 
}

trajcIa <- traj
#trajcIa %>%
  #filter(cIa == 0.005) %>%
  ggplot(trajcIa) +
    geom_point(data=GData, aes(Age, ltow_AYV(Length)), alpha=0.1) +
    geom_line(size=1 , aes(t, mass, color = as.factor(Temp))) +
    facet_wrap(~cIa, labeller = label_both) +
    #geom_point(data=GData, aes(Age, ltow_AYV(Length)), alpha=0.1) +
    # ylim(0,0.012) + #ylim(0,NA) +
    # xlim(0,5) + #ylim(0,NA) +
    theme_bw() + 
   scale_colour_brewer(palette="Dark2")
```

```{r}
### ADAPTATION IN OTHER VARIABLES ####
T <- seq(285,289,0.5) # temperature range
kappa <- 0.85# seq(0.8,1,0.05) # kappa range
ha_Ad <- seq(0.5,5,0.5) # kappa range
# T <- seq(280,292,0.25) # temperature range
# kappa <-seq(0,1,0.025) # kappa range
Y <- 1 # feeding levels

Res_lam <- matrix(ncol = 4+1, nrow = length(ha_Ad)*length(T)*length(Y)*length(kappa)) # assuming 40 here from files
Res_v  <-  matrix(ncol = 4+n+1, nrow = length(ha_Ad)*length(T)*length(Y)*length(kappa)) # assuming 40 here from files
Res_w  <-  matrix(ncol = 4+n+1, nrow = length(ha_Ad)*length(T)*length(Y)*length(kappa)) # assuming 40 here from files

parsK <- as.matrix(expand.grid(T,kappa,Y, ha_Ad))
colnames(parsK) <- c("T","kappa","Y","ha")

for (i in 1:nrow(parsK)){
  res <- wvlambda.projection(K.matrix(parsK[i,]))
  Res_lam[i,] <- c(parsK[i,],res$lam) #c(T[d],kappa[e],Y[f], res$lambda)
  Res_v[i,]   <- c(parsK[i,],res$v) #REPRODUCTIVE VALUES
  Res_w[i,]   <- c(parsK[i,],res$w) #STABLE STRUCTURE
}

colnames(Res_lam) <- c("T","kappa","Y","ha","Lambda")
colnames(Res_v) <- c("T","kappa","Y","ha","0",x)
colnames(Res_w) <- c("T","kappa","Y","ha","0",x)
```

```{r}
library(scales)
library(patchwork)

as_tibble(Res_lam) %>%
  #filter(T %in% c(277, 279, 281, 283, 285, 287, 289)) %>%
  ggplot(., aes(ha, Lambda, color = as.factor(T))) +
  geom_line(size=0.5) +
  ylab(expression(lambda~(Fitness))) +
  xlab(expression(ha~(Growth~Allocation))) +
  labs(color = "Temp [K]") +
  theme_bw()
a
### PLOT A SURFACE OF FITNESS OVER TEMP (x) AND KAPPA (y)
maxl<- as.data.frame(Res_lam) %>% 
        group_by(T) %>%
        slice_max(Lambda)


b <- 
  ggplot(as_tibble(Res_lam), aes(T,ha)) +
   geom_raster(aes(fill=round(Lambda, 4))) + #, interpolate = TRUE) +
   geom_smooth(data=maxl ,aes(T,ha), size=1, se=FALSE) +
   geom_point(data=maxl ,aes(T,ha),size=0.1) +
   scale_fill_gradientn(
     limits = c(0,max(as.data.frame(Res_lam[,'Lambda'])+0.0001)),
     colours = c("black","white","yellow","red"),
     values = rescale(c(0,0.99999,1, round(max(as.data.frame(Res_lam[,'Lambda'])), 6)), to=c(0,1)),
     breaks = c(0,1),
     #labels=c("0",1,round(max(as.data.frame(Res_lam[,'Lambda'])),3)),
     name = expression(lambda)) +
  scale_x_continuous(breaks = seq(min(Res_lam[,"T"]), max(Res_lam[,"T"]), by = 1),expand = c(0, 0))  +
  scale_y_continuous(expand = c(0, 0)) +
  #ggtitle("kappa Size-dependent") +
  #ggtitle("Temperature effect independent of size ") +
  theme_bw()
b
  ## PLOT STABLE STRUCTURE W AS A FUNCTION OF KAPPA AND/OR TEMP ####
#colnames(Res_w) <- c("T","kappa","Y","0",x)
as.data.frame(Res_w) %>%
  filter(T %in% 283) %>%
  filter(kappa %in% 0.92) #%>%
#plot()  
Res_w_long <- pivot_longer(as.data.frame(Res_w), cols = c(5:ncol(Res_w)), 
                           names_to = "Size", values_to ="biom") # not use column 4 & 5 (eggstage and recruits)

c <- Res_w_long %>%
  #filter(T %in% c(277, 281, 283, 287, 290)) %>%
  #filter(as.character(T) %in% c(283,285,287,289, 291)) %>%
  filter(as.character(T) %in% c(285,287,289)) %>%
  #filter(kappa %in% 0.8) %>% #Floating point issue when comparing vector, therefore the use of %in%, can also use near()
  filter(as.character(ha) %in% 5) %>% #Floating point issue when comparing vector, therefore the use of %in%, can also use near()
  ggplot(., aes(as.numeric(Size), biom, color = as.factor(T))) +
  ggtitle("Stable structure for small Sizes, kappa=0.8") + 
  geom_line(size=0.5) +
  ylab("Stable structure w") +
  xlab("Size") +
  xlim(0,2000) +
  theme_bw() +
  theme(legend.position="none",
  plot.title = element_text(size = 12))+
  labs(color = "Temp [K]")
c
d <- Res_w_long %>%
#  filter(T %in% c(283, 285, 287, 289, 290)) %>%
  #filter(kappa %in% 0.8) %>% #Floating point issue when comparing vector, therefore the use of %in%, can also use near()
  filter(as.character(ha) %in% 5) %>% #Floating point issue when comparing vector, therefore the use of %in%, can also use near()
  filter(as.character(T) %in% c(285,287,289)) %>%
  #  filter(as.character(T) %in% c(283, 285, 287, 289, 290)) %>%
  #filter(kappa %in% 0.8) %>% #Floating point issue when comparing vector, therefore the use of %in%, can also use near()
  #filter(as.character(kappa) %in% "0.92") %>% #Floating point issue when comparing vector, therefore the use of %in%, can also use near()
    ggplot(., aes(as.numeric(Size), biom, color = as.factor(T))) +
  ggtitle("Stable struct w/o Age 1, kappa=0.8") + 
  geom_line(size=0.5) +
  ylab("Stable structure w") +
  xlab("Size") +
  ylim(0,5e-8)+
  theme_bw()+
  theme(legend.position="none", 
  plot.title = element_text(size = 12)) +
  labs(color = "Temp [K]")
d
# Res_w_long %>%
#   filter(kappa %in% c(0.75,0.8,0.85)) %>% #Floating point issue when comparing vector, therefore the use of near()
#   filter(T %in% 283) %>% 
#   ggplot(., aes(as.numeric(Size), biom, color = as.factor(kappa))) +
#   ggtitle("Stable structure over Size with three kappas at T0") + 
#   geom_line(size=0.8) +
#   ylab("Stable structure w") +
#   xlab("Size") +
#   ylim(0,2e-8)+
#   theme_bw()+
#   labs(color = expression(kappa))


### PLOT REPRODUCTIVE VALUES V AS A FUNCTION OF KAPPA AND/OR TEMP ####
colnames(Res_v) <- c("T","kappa","Y","0",x)
Res_v_long <- pivot_longer(as_tibble(Res_v), cols = c(5:ncol(Res_v)), 
                           names_to = "Size", values_to ="biom") # not use column 4 & 11 (eggstage and recruits)

e<-Res_v_long %>%
#  filter(T %in% c(277, 281, 283, 287, 290)) %>%
  #filter(kappa %in% 0.8) %>% #Floating point issue when comparing vector, therefore the use of %in%, can also use near()
  filter(as.character(T) %in% c(285, 287, 289)) %>%
  filter(as.character(ha) %in% c(0.5,1,1.5)) %>% #Floating point issue when comparing vector, therefore the use of %in%, can also use near()
  ggplot(., aes(as.numeric(Size), biom, color = as.factor(T), linetype = as.factor(ha))) +#, linetype = as.factor(kappa))) +
  ggtitle("Repro. values over Size") + 
  geom_line(size=0.8) +
  ylab("Reproductive value V") +
  xlab("Size")+
  theme_bw() +
  labs(color = "Temp [K]")

e
library(gridExtra)
#pdf("DEBIPM_xxx_xxx.pdf", width = 8, height = 6)
(a+b) / (c+d+e)
```